USE subway_gdl;

-- INSERTS THE SUBWAY STATIONS
INSERT INTO stations_delete (name) VALUES
("Audiorio"), --Auditorio
("Peririco Norte"), --Periférico Norte
("Dermatológico"),
("Atemaj"), --Atemajac
("División del Norte"),
("Ávila Camacho"),
("Mezquitán"),
("Refugio"),
("Juárez"),
("Mexicaltzingo"),
("Whashington"), -- Washington
("Santa Filomena"),
("Unidad Deportiva"),
("Urdaneta"),
("18 de Marzo"),
("Isla Raza"),
("Patria Sur"),
("España"),
("Santuario Mártires de Cristo"),
("Periférico Sur"),
("Juárez"),
("Plaza Universidad"),
("San Juan de Dios"),
("Belisario Domínguez"),
("Oblatos"),
("Cristóbal de Oñate"),
("San Andrés"),
("San Jacinto"),
("La Aurora"),
("Tetlán"),
("Arcos de Zapopan"),
("Periférico Belenes"),
("Mercado del Mar"),
("Zapopan Centro"),
("Plaza Patria"),
("Circunvalación Country"),
("Ávila Camacho"),
("La Normal"),
("Santuario"),
("Guadalajara Centro"),
("Independencia"),
("Plaza de la Bandera"),
("Cucei"),
("Revolución"),
("Río Nilo"),
("Tlaquepaque Centro"),
("Lázaro Cárdenas"),
("Central de Autobuses"),
("Lázaro de Guerrero"),
("Benito Cárdenas");